package org.celo.contractkit;

public enum CeloContract {
    Accounts,
    Attestations,
    BlockchainParameters,
    DoubleSigningSlasher,
    DowntimeSlasher,
    Election,
    EpochRewards,
    Escrow,
    Exchange,
    ExchangeEUR,
    ExchangeBRL,
    FeeCurrencyWhitelist,
    Freezer,
    GasPriceMinimum,
    GoldToken,
    Governance,
    LockedGold,
    MultiSig,
    Random,
    Registry,
    Reserve,
    SortedOracles,
    StableToken,
    StableTokenEUR,
    StableTokenBRL,
    TransferWhitelist,
    Validators,
}
